# setwd('E:\\mine\\work\\pancreatic\\version3\\code\\Fig4\\B-Regulon-NEN')
data=read.table('heatmap-NEN-20210104.txt',sep='\t',head=TRUE)
data1=data[,-1]
library(pheatmap)
data1=as.matrix(data1)
data1=t(scale(t(data1)))
rownames(data1)=as.character(data$TF)
color0 = colorRampPalette(c('blue','white','red'))(7)
library(circlize)
col_fun = colorRamp2(c(-2,-1,0,1,2), c("navy",color0[3], "white",color0[5], "firebrick3"))
col_fun1 = colorRamp2(c(0, 3, 12), c("#3363aa", "white", "#faf513"))
data2=read.table('rankNEN-20210104.txt',sep='\t',header=TRUE)
library(ComplexHeatmap)
anno=c(rep('Exocrine',41),rep('Neuroendocrine',4))
ha = HeatmapAnnotation(subtype = anno,col = list(subtype=c('Exocrine' = "grey", 'Neuroendocrine'='#e64b35')))
hb=Heatmap(data1,col=col_fun,cluster_rows = FALSE,cluster_columns = FALSE,show_row_dend = FALSE,row_names_side = c( "left"),show_column_names=FALSE,top_annotation=ha,row_names_gp = gpar(fontsize = 10))
data2=-log(data2,10)
hc=Heatmap(data2,col=col_fun1,cluster_rows = FALSE,cluster_columns = FALSE,show_row_dend = FALSE,row_names_side = c( "left"),show_row_names = FALSE,width = unit(0.5, "cm"))
pdf('heatmap-NEN-20210104.pdf',width=6,height=9)
hb+hc
dev.off()