# setwd('E:\\mine\\work\\pancreatic\\version3\\code\\Fig4\\B-Regulon-subtype')
data=read.table('heatmap-PDAC-20210104.txt',sep='\t',head=TRUE)
data1=data[,-1]
library(pheatmap)
data1=as.matrix(data1)
data1=t(scale(t(data1)))
rownames(data1)=as.character(data$TF)
color0 = colorRampPalette(c('blue','white','red'))(7)
library(circlize)
col_fun = colorRamp2(c(-2,-1,0,1,2), c("navy",color0[3], "white",color0[5], "firebrick3"))
col_fun1 = colorRamp2(c(0, 3, 6), c("#3363aa", "white", "#faf513"))
data2=read.table('rank-PDAC-20210104.txt',sep='\t',header=TRUE)
library(ComplexHeatmap)
anno=c(rep('Classical-like',7),rep('Basal-like',11),rep('Classical-Progenitor',9),rep('Glycomet',13))
ha = HeatmapAnnotation(subtype = anno,col = list(subtype=c("Classical-like" = "#4dbbd5", "Basal-like" = "#00a087", "Classical-Progenitor" = "#f39b7f", 'Glycomet'="#8491b4")))
hb=Heatmap(data1,col=col_fun,cluster_rows = FALSE,cluster_columns = FALSE,show_row_dend = FALSE,row_names_side = c( "left"),show_column_names=FALSE,top_annotation=ha,row_names_gp = gpar(fontsize = 10))
data2=-log(data2,10)
hc=Heatmap(data2,col=col_fun1,cluster_rows = FALSE,cluster_columns = FALSE,show_row_dend = FALSE,row_names_side = c( "left"),show_row_names = FALSE,width = unit(1.6, "cm"))
pdf('heatmap-PDAC-20210104.pdf',width=7,height=9)
hb+hc
dev.off()